apiVersion: v2
name: onek3s
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: "4.6.0"
    condition: components.nginx
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: "1.11.1"
    condition: components.certManager
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: "11.5.6"
    condition: components.mariadb
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: "12.2.4"
    condition: components.minio
